local M = {}

M.not_used = { ["Q"] = "does not start Ex mode" }

M.same_as = {
  ["<C-a>"] = { "g<C-a>" },
  ["<C-x>"] = { "g<C-x>" },
  ["<BS>"] = { "<C-h>" },
  ["<Esc>"] = { "<C-c>" },
  ["C"] = { "R", "S" },
  ["D"] = { "X" },
  ["c"] = { "s" },
  ["ab"] = { "a(", "a)" },
  ["a<"] = { "a>" },
  ["a["] = { "a]" },
  ["aB"] = { "a{", "a{" },
  ["ib"] = { "i(", "i)" },
  ["i<"] = { "i>" },
  ["i["] = { "i]" },
  ["iB"] = { "i{", "i{" },
}

M.mode = {
  ["<C-\\>"] = {
    name = "mode",
    ["<C-n>"] = "stop Visual mode",
    ["<C-g>"] = "go to mode specified with 'insertmode'",
  },
}

M.mapping = {
  ["a"] = { name = "around" },
  ["i"] = { name = "inside" },
  ["<C-a>"] = "Ψ_add N to number in highlighted text",
  ["<C-g>"] = "toggle between Visual mode and Select mode",
  ["<BS>"] = "Ψ_Select mode: delete highlighted area",
  ["<C-o>"] = "switch from Select to Visual mode for one command",
  ["<C-v>"] = "make Visual mode blockwise or stop Visual mode",
  ["<C-x>"] = "Ψ_subtract N from number in highlighted text",
  ["<Esc>"] = "stop Visual mode",
  ["<C-]>"] = "jump to highlighted tag",
  ["!"] = "ζ,Ψ_filter the highlighted lines through the ζ command",
  [":"] = "start a command-line with the highlighted lines as a range",
  ["<LT>"] = "Ψ_shift the highlighted lines one 'shiftwidth' left",
  ["="] = "Ψ_filter the highlighted lines through 'equalprg'",
  [">"] = "Ψ_shift the highlighted lines one 'shiftwidth' right",
  ["A"] = "Ψ_block mode: append same text after the highlighted area",
  ["C"] = "ΛΨ_delete the highlighted lines, start insert",
  ["D"] = "ΛΨ_delete the highlighted lines",
  ["I"] = "Ψ_block mode: insert same text before the highlighted area",
  ["J"] = "Ψ_join the highlighted lines",
  ["K"] = "run 'keywordprg' on the highlighted area",
  ["O"] = "move horizontally to other corner of area",
  ["U"] = "Ψ_make highlighted area uppercase",
  ["V"] = "make Visual mode linewise or stop Visual mode",
  ["Y"] = "Λ_yank the highlighted lines",
  ['a"'] = "extend Θ with a double quoted string",
  ["a'"] = "extend Θ with a single quoted string",
  ["a<LT>"] = "extend Θ with a <> block",
  ["aB"] = "extend Θ with a {} block",
  ["aW"] = "extend Θ with a WORD",
  ["a["] = "extend Θ with a [] block",
  ["a`"] = "extend Θ with a backtick quoted string",
  ["ab"] = "extend Θ with a () block",
  ["ap"] = "extend Θ with a paragraph",
  ["as"] = "extend Θ with a sentence",
  ["at"] = "extend Θ with a tag block",
  ["aw"] = "extend Θ with a word",
  ["c"] = "ΛΨ_delete highlighted area, start insert",
  ["d"] = "ΛΨ_delete highlighted area",
  ["gJ"] = "Ψ_join the highlighted lines without inserting spaces",
  ["gq"] = "Ψ_format the highlighted lines",
  ["gv"] = "exchange current and previous highlighted area",
  ['i"'] = "extend Θ with a double quoted string (without quotes)",
  ["i'"] = "extend Θ with a single quoted string (without quotes)",
  ["i<LT>"] = "extend Θ with inner <> block",
  ["iB"] = "extend Θ with inner {} block",
  ["iW"] = "extend Θ with inner WORD",
  ["i["] = "extend Θ with inner [] block",
  ["i`"] = "extend Θ with a backtick quoted string (without the backticks)",
  ["ib"] = "extend Θ with inner () block",
  ["ip"] = "extend Θ with inner paragraph",
  ["is"] = "extend Θ with inner sentence",
  ["it"] = "extend Θ with inner tag block",
  ["iw"] = "extend Θ with inner word",
  ["o"] = "move Δ to other corner of area",
  ["r"] = "Ψ_replace highlighted area with a character",
  ["u"] = "Ψ_make highlighted area lowercase",
  ["v"] = "make Visual mode charwise or stop Visual mode",
  ["x"] = "ΛΨ_delete the highlighted area",
  ["y"] = "Λ_yank the highlighted area",
  ["~"] = "Ψ_swap case for the highlighted area",
}

return M
