local wk = require("which-key")

local visual_binds = {
  ["<C-\\>"] = {
    name = "mode",
    ["<C-n>"] = "stop Visual mode",
    ["<C-g>"] = "go to mode specified with 'insertmode'",
  },
  ["<C-a>"] = "↶ add N to number in highlighted text",
  ["<C-c>"] = "stop Visual mode",
  ["<C-g>"] = "toggle between Visual mode and Select mode",
  ["<BS>"] = "↶ Select mode: delete highlighted area",
  ["<C-h>"] = "↶ same as <BS>",
  ["<C-o>"] = "switch from Select to Visual mode for one command",
  ["<C-v>"] = "make Visual mode blockwise or stop Visual mode",
  ["<C-x>"] = "↶ subtract N from number in highlighted text",
  ["<Esc>"] = "stop Visual mode",
  ["<C-]>"] = "jump to highlighted tag",
  ["!"] = "↶ filter the highlighted lines through the external command {filter}",
  [":"] = "start a command-line with the highlighted lines as a range",
  ["<LT>"] = "↶ shift the highlighted lines one 'shiftwidth' left",
  ["="] = "↶ filter the highlighted lines through the external program given with the 'equalprg' option",
  [">"] = "↶ shift the highlighted lines one 'shiftwidth' right",
  ["A"] = "↶ block mode: append same text in all lines, after the highlighted area",
  ["C"] = "↶ delete the highlighted lines and start insert",
  ["D"] = "↶ delete the highlighted lines",
  ["I"] = "↶ block mode: insert same text in all lines, before the highlighted area",
  ["J"] = "↶ join the highlighted lines",
  ["K"] = "run 'keywordprg' on the highlighted area",
  ["O"] = "Move horizontally to other corner of area.",
  ["R"] = "↶ delete the highlighted lines and start insert",
  ["S"] = "↶ delete the highlighted lines and start insert",
  ["U"] = "↶ make highlighted area uppercase",
  ["V"] = "make Visual mode linewise or stop Visual mode",
  ["X"] = "↶ delete the highlighted lines",
  ["Y"] = "yank the highlighted lines",
  -- ['a'] = {
  --   name = 'around',
  --   ['"'] = 'extend highlighted area with a double quoted string',
  --   ['\''] = 'extend highlighted area with a single quoted string',
  --   ['('] = 'same as ab',
  --   [')'] = 'same as ab',
  --   ['<LT>'] = 'extend highlighted area with a <> block',
  --   ['>'] = 'same as a<',
  --   ['B'] = 'extend highlighted area with a {} block',
  --   ['W'] = 'extend highlighted area with "a WORD"',
  --   ['['] = 'extend highlighted area with a [] block',
  --   [']'] = 'same as a[',
  --   ['`'] = 'extend highlighted area with a backtick quoted string',
  --   ['b'] = 'extend highlighted area with a () block',
  --   ['p'] = 'extend highlighted area with a paragraph',
  --   ['s'] = 'extend highlighted area with a sentence',
  --   ['t'] = 'extend highlighted area with a tag block',
  --   ['w'] = 'extend highlighted area with "a word"',
  --   ['{'] = 'same as aB',
  --   ['}'] = 'same as aB'
  -- },
  ["c"] = "↶ delete highlighted area and start insert",
  ["d"] = "↶ delete highlighted area",
  ["g"] = {
    ["<C-a>"] = "↶ add N to number in highlighted text",
    ["<C-x>"] = "↶ subtract N from number in highlighted text",
    ["J"] = "↶ join the highlighted lines without inserting spaces",
    ["q"] = "↶ format the highlighted lines",
    ["v"] = "exchange current and previous highlighted area",
  },
  -- ['i'] = {
  --   name = 'inside',
  --   ['"'] = 'extend highlighted area with a double quoted string (without quotes)',
  --   ['\''] = 'extend highlighted area with a single quoted string (without quotes)',
  --   ['('] = 'same as ib',
  --   [')'] = 'same as ib',
  --   ['<LT>'] = 'extend highlighted area with inner <> block',
  --   ['>'] = 'same as i<',
  --   ['B'] = 'extend highlighted area with inner {} block',
  --   ['W'] = 'extend highlighted area with "inner WORD"',
  --   ['['] = 'extend highlighted area with inner [] block',
  --   [']'] = 'same as i[',
  --   ['`'] = 'extend highlighted area with a backtick quoted string (without the backticks)',
  --   ['b'] = 'extend highlighted area with inner () block',
  --   ['p'] = 'extend highlighted area with inner paragraph',
  --   ['s'] = 'extend highlighted area with inner sentence',
  --   ['t'] = 'extend highlighted area with inner tag block',
  --   ['w'] = 'extend highlighted area with "inner word"',
  --   ['{'] = 'same as iB',
  --   ['}'] = 'same as iB'
  -- },
  ["o"] = "move cursor to other corner of area",
  ["r"] = "↶ replace highlighted area with a character",
  ["s"] = "↶ delete highlighted area and start insert",
  ["u"] = "↶ make highlighted area lowercase",
  ["v"] = "make Visual mode charwise or stop Visual mode",
  ["x"] = "↶ delete the highlighted area",
  ["y"] = "yank the highlighted area",
  ["~"] = "↶ swap case for the highlighted area",
}

wk.register(visual_binds, { mode = "v", preset = true })
