local M = {}

M.objects = {
  ["a"] = { name = "around" },
  ["i"] = { name = "inside" },
  ["a\""] = "extend highlighted area with a double quoted string",
  ["a'"] = "extend highlighted area with a single quoted string",
  ["a("] = "same as ab",
  ["a)"] = "same as ab",
  ["a<LT>"] = "extend highlighted area with a <> block",
  ["a>"] = "same as a<",
  ["aB"] = "extend highlighted area with a {} block",
  ["aW"] = "extend highlighted area with \"a WORD\"",
  ["a["] = "extend highlighted area with a [] block",
  ["a]"] = "same as a[",
  ["a`"] = "extend highlighted area with a backtick quoted string",
  ["ab"] = "extend highlighted area with a () block",
  ["ap"] = "extend highlighted area with a paragraph",
  ["as"] = "extend highlighted area with a sentence",
  ["at"] = "extend highlighted area with a tag block",
  ["aw"] = "extend highlighted area with \"a word\"",
  ["a{"] = "same as aB",
  ["a}"] = "same as aB",
  ["i\""] = "extend highlighted area with a double quoted string (without quotes)",
  ["i'"] = "extend highlighted area with a single quoted string (without quotes)",
  ["i("] = "same as ib",
  ["i)"] = "same as ib",
  ["i<LT>"] = "extend highlighted area with inner <> block",
  ["i>"] = "same as i<",
  ["iB"] = "extend highlighted area with inner {} block",
  ["iW"] = "extend highlighted area with \"inner WORD\"",
  ["i["] = "extend highlighted area with inner [] block",
  ["i]"] = "same as i[",
  ["i`"] = "extend highlighted area with a backtick quoted string (without the backticks)",
  ["ib"] = "extend highlighted area with inner () block",
  ["ip"] = "extend highlighted area with inner paragraph",
  ["is"] = "extend highlighted area with inner sentence",
  ["it"] = "extend highlighted area with inner tag block",
  ["iw"] = "extend highlighted area with \"inner word\"",
  ["i{"] = "same as iB",
  ["i}"] = "same as iB",
}

M.mapping = {
  ["<C-\\>"] = {
    name = "mode",
    ["<C-n>"] = "stop Visual mode",
    ["<C-g>"] = "go to mode specified with 'insertmode'",
  },
  ["<C-a>"] = "↶ add N to number in highlighted text",
  ["<C-c>"] = "stop Visual mode",
  ["<C-g>"] = "toggle between Visual mode and Select mode",
  ["<BS>"] = "↶ Select mode: delete highlighted area",
  ["<C-h>"] = "↶ same as <BS>",
  ["<C-o>"] = "switch from Select to Visual mode for one command",
  ["<C-v>"] = "make Visual mode blockwise or stop Visual mode",
  ["<C-x>"] = "↶ subtract N from number in highlighted text",
  ["<Esc>"] = "stop Visual mode",
  ["<C-]>"] = "jump to highlighted tag",
  ["!"] = "↶ filter the highlighted lines through the external command {filter}",
  [":"] = "start a command-line with the highlighted lines as a range",
  ["<LT>"] = "↶ shift the highlighted lines one 'shiftwidth' left",
  ["="] = "↶ filter the highlighted lines through the external program given with the 'equalprg' option",
  [">"] = "↶ shift the highlighted lines one 'shiftwidth' right",
  ["A"] = "↶ block mode: append same text in all lines, after the highlighted area",
  ["C"] = "↶ delete the highlighted lines and start insert",
  ["D"] = "↶ delete the highlighted lines",
  ["I"] = "↶ block mode: insert same text in all lines, before the highlighted area",
  ["J"] = "↶ join the highlighted lines",
  ["K"] = "run 'keywordprg' on the highlighted area",
  ["O"] = "Move horizontally to other corner of area.",
  ["R"] = "↶ delete the highlighted lines and start insert",
  ["S"] = "↶ delete the highlighted lines and start insert",
  ["U"] = "↶ make highlighted area uppercase",
  ["V"] = "make Visual mode linewise or stop Visual mode",
  ["X"] = "↶ delete the highlighted lines",
  ["Y"] = "yank the highlighted lines",

  ["c"] = "↶ delete highlighted area and start insert",
  ["d"] = "↶ delete highlighted area",
  ["g"] = {
    ["<C-a>"] = "↶ add N to number in highlighted text",
    ["<C-x>"] = "↶ subtract N from number in highlighted text",
    ["J"] = "↶ join the highlighted lines without inserting spaces",
    ["q"] = "↶ format the highlighted lines",
    ["v"] = "exchange current and previous highlighted area",
  },
  ["o"] = "move cursor to other corner of area",
  ["r"] = "↶ replace highlighted area with a character",
  ["s"] = "↶ delete highlighted area and start insert",
  ["u"] = "↶ make highlighted area lowercase",
  ["v"] = "make Visual mode charwise or stop Visual mode",
  ["x"] = "↶ delete the highlighted area",
  ["y"] = "yank the highlighted area",
  ["~"] = "↶ swap case for the highlighted area",
}

return M
